### ISSUE TITLE
Connection with module humix-conversation-module is always failed

### ISSUE THREAD

**Issue by heretse** [project-humix/humix-think#10]
Starting logs for Humix-Sense are shown below and other detail configurations please see the  attached file -> [Archive.zip](https://github.com/project-humix/humix-think/files/692869/Archive.zip)

2017-01-09T07:26:45.961Z [ INFO] Humix-Sense: Init Humix Sense. Using Think URL:http://xxxxx.mybluemix.net
2017-01-09T07:26:46.120Z [ INFO] Humix-Sense: loading module : /home/pi/humix-sense/modules/core/humix-conversation-module
2017-01-09T07:26:46.181Z [ INFO] Humix-Sense: process for module [/home/pi/humix-sense/modules/core/humix-conversation-module] spawned
^[[B2017-01-09T07:26:49.013Z [ERROR] Humix-Sense: Connection to Think is broken, message:
2017-01-09T07:26:51.845Z [ INFO] Humix-Sense: Connected SenseId humix-talkbot to Think successfully.
2017-01-09T07:26:53.416Z [ INFO] Humix-Sense: Receive registration :{"moduleName":"humix-conversation-module","commands":["tts"],"events":["stt"],"log":{"file":"humix-conversation-module.log","fileLevel":"info","consoleLevel":"debug"}}
2017-01-09T07:26:53.419Z [ INFO] Humix-Sense: subscribing topic:humix.sense.humix-conversation-module.event.stt
2017-01-09T07:27:00.069Z [ERROR] Humix-Sense: connection with module humix-conversation-module failed
2017-01-09T07:27:03.104Z [ERROR] Humix-Sense: connection with module humix-conversation-module failed

**Comment by jeffffrey** [comment]
Hmm... not immediately clear to me what caused the problem. The attached configuration looks fine ( although ITRI service is missing password) .
Can you do me a favor ? edit /home/pi/humix-sense/modules/core/humix-conversation-module/humix-conversation.js , and set log level of file logger to "debug". I.e. 

var config = {
    "moduleName" : "humix-conversation-module",
    "commands" : ["tts"],
    "events" : ["stt"],
    "log" : {
        file : 'humix-conversation-module.log',
        fileLevel : '**debug**',
        consoleLevel : 'debug'
      }
};


then remove existing /home/pi/.humix/humix-conversation-module.log and start over again. Please attach the new humix-conversation-module.log here for troubleshooting. 

Thanks.

**Comment by heretse** [comment]
This issue was happened on my Raspberry Pi 2 (model B) device, but it works fine on my current device which is Raspberry Pi 3. I need to reproduce this environment for detail logs and provide to you.

Thanks.

**Comment by jeffffrey** [comment]
ok, then I am going to give it a try on Raspberry Pi2 as well. That's a good hint. 

Please share with me if you got more information. Thanks.

**Comment by heretse** [comment]
Hi Jeffffrey 

I got this error stack trace logs as shown belows.

> ========= starting ===========
2017-01-18T15:21:57.132Z [ INFO] humix-conversation-module: module registration completed
2017-01-18T15:21:57.135Z [DEBUG] humix-conversation-module: subscribing command topic:humix.sense.humix-conversation-module.command.tts
2017-01-18T15:21:57.137Z [ INFO] humix-conversation-module: access config
2017-01-18T15:21:57.141Z [ INFO] humix-conversation-module: loading config: {"lang":"cht","stt-engine":"watson","tts-engine":"itri","stt":{"watson":{"username":"1bfd6fc3-4135-443a-b089-b1bec7349c31","passwd":"quZyb0PLAHdY"},"google":{"username":"winston_hsieh@gemteks.com","passwd":"6323zwnn9759","googleCredentialFile":"/home/pi/.humix/Humix-TalkBot-bc9ec15804e9.json","googleProjectName":"Humix TalkBot","googleLan":"cmn-Hant-TW"}},"tts":{"watson":{"username":"d8786655-5960-4d39-a771-21f4b90f0f35","passwd":"ovw3Lkiy0JgT"},"iflytek":{"appid":"<app_id>"},"itri":{"username":"heretse","passwd":"nn9759","speaker":"Bruce"}}}
2017-01-18T15:21:57.142Z [ INFO] humix-conversation-module: Conversation instance created.
using config:{"lang":"cht","stt-engine":"watson","tts-engine":"itri","stt":{"watson":{"username":"1bfd6fc3-4135-443a-b089-b1bec7349c31","passwd":"quZyb0PLAHdY"},"google":{"username":"winston_hsieh@gemteks.com","passwd":"6323zwnn9759","googleCredentialFile":"/home/pi/.humix/Humix-TalkBot-bc9ec15804e9.json","googleProjectName":"Humix TalkBot","googleLan":"cmn-Hant-TW"}},"tts":{"watson":{"username":"d8786655-5960-4d39-a771-21f4b90f0f35","passwd":"ovw3Lkiy0JgT"},"iflytek":{"appid":"<app_id>"},"itri":{"username":"heretse","passwd":"nn9759","speaker":"Bruce"}}}
2017-01-18T15:21:57.144Z [ INFO] humix-conversation-module: Using stt-engine:watson
created waton stt instance
2017-01-18T15:21:58.540Z [DEBUG] humix-conversation-module/WatsonSTT: connecting..
2017-01-18T15:21:58.542Z [ INFO] humix-conversation-module/WatsonSTT: inited watson stt. Model: zh-CN_BroadbandModel
/home/pi/humix-sense/modules/_core/humix-conversation-module/node_modules/mic/lib/mic.js:65
            : spawn('arecord', ['-c', channels, '-r', rate, '-f', format, '-D', device], audioProcessOptions);
>                                                                                ^
ReferenceError: device is not defined
    at Object.start (/home/pi/humix-sense/modules/_core/humix-conversation-module/node_modules/mic/lib/mic.js:65:81)
    at Conversation.initMic (/home/pi/humix-sense/modules/_core/humix-conversation-module/lib/conversation.js:222:17)
    at Conversation.init (/home/pi/humix-sense/modules/_core/humix-conversation-module/lib/conversation.js:133:14)
    at HumixSense.<anonymous> (/home/pi/humix-sense/modules/_core/humix-conversation-module/humix-conversation.js:49:18)
    at emitOne (events.js:96:13)
    at HumixSense.emit (events.js:188:7)
    at /home/pi/humix-sense/modules/_core/humix-conversation-module/node_modules/humix-sense/index.js:264:14
    at Object.callback (/home/pi/humix-sense/modules/_core/humix-conversation-module/node_modules/nats/lib/nats.js:1133:5)
    at Client.processMsg (/home/pi/humix-sense/modules/_core/humix-conversation-module/node_modules/nats/lib/nats.js:892:11)
    at Client.processInbound (/home/pi/humix-sense/modules/_core/humix-conversation-module/node_modules/nats/lib/nats.js:824:14)

**Comment by heretse** [comment]
Hi Jeffffrey

I have fixed this issue by uncomment the 28th line in mic.js file.

`var mic = function mic(options, parentLogger) {
    options = options || {};

    if(!parentLogger){

        logger = bunyan.createLogger({name: "mic"});
    }else{

         logger = parentLogger.child({loc: 'mic'});
    }

    var that = {};
    var endian = options.endian || 'little';
    var bitwidth = options.bitwidth || '16';
    var encoding = options.encoding || 'signed-integer';
    var rate = options.rate || '16000';
    var channels = options.channels || '1';
    //var device = options.device || 'plughw:1,0';
    var exitOnSilence = options.exitOnSilence || 0;
    var fileType = options.fileType || 'wav';
    var debug = options.debug || false;
    var format, formatEndian, formatEncoding;
    var audioProcess = null;
    var infoStream = new PassThrough;
    var audioStream = new IsSilence(logger, {debug: debug});
    var audioProcessOptions = {
        stdio: ['ignore', 'pipe', 'ignore']
    }; `

**Comment by jeffffrey** [comment]
ah.. good point. It should not be explicitly specified there, or at least we should provide a configurable option. Nice catch. I'll merge the change in my mic repo. Thanks.
