### ISSUE TITLE
Deploy failed by humix-settings.js

### ISSUE THREAD

**Issue by heretse** [project-humix/humix-think#13]
Root Cause:
Reference Error: path is not defined

Solution:
Add the definition for path in your require
`var path = require('path');
var humixSettings = module.exports = {
`

Detail log:
2017-05-26T15:34:05.35+0800 [APP/0] ERR /home/vcap/app/humix-settings.js:51
2017-05-26T15:34:05.35+0800 [APP/0] ERR ReferenceError: path is not defined
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Object.<anonymous> (/home/vcap/app/humix-settings.js:51:15)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Module._compile (module.js:570:32)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Object.Module._extensions..js (module.js:579:10)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Module.load (module.js:487:32)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at tryModuleLoad (module.js:446:12)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Function.Module._load (module.js:438:3)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Module.require (module.js:497:17)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at require (internal/module.js:20:19)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Object.<anonymous> (/home/vcap/app/server/app.js:30:21)
2017-05-26T15:34:05.35+0800 [APP/0] ERR     at Module._compile (module.js:570:32)

**Comment by jeffffrey** [comment]
Nice catch. Fixed in 25b320460a6dbd7820a3e2eb5dbb5ff9ce4d2de2
