### ISSUE TITLE
Humix-think restarted when accessing all sense devices for the first time

### ISSUE THREAD

**Issue by jeffffrey** [project-humix/humix-think#3]
Saw this from cf logs. 

2016-08-14T22:57:06.55+0800 [RTR/0]      OUT humix-demo.mybluemix.net - [14/08/2016:14:57:06.537 +0000] "GET /assets/images/gridView.png HTTP/1.1" 200 0 209 "http://humix-demo.mybluemix.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0" 192.155.237.114:26788 x_forwarded_for:"36.228.156.45" x_forwarded_proto:"http" vcap_request_id:4a93face-cd8d-47f3-7c23-78b9a85f5da6 response_time:0.014437867 app_id:253db17e-cb85-47c2-9440-e01805cc0a9d x_global_transaction_id:"3812595287"
2016-08-14T22:57:06.58+0800 [App/0]      OUT doc:undefined
2016-08-14T22:57:06.59+0800 [App/0]      ERR /home/vcap/app/api/devices.js:128
2016-08-14T22:57:06.59+0800 [App/0]      ERR       docs.rows.forEach(function(doc) {
2016-08-14T22:57:06.59+0800 [App/0]      ERR           ^
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at /home/vcap/app/api/devices.js:128:11
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at Request._callback (/home/vcap/app/node_modules/nano/nano.js:319:16)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at Request.self.callback (/home/vcap/app/node_modules/nano/node_modules/request/request.js:236:22)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at emitTwo (events.js:87:13)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at emitNone (events.js:72:20)
2016-08-14T22:57:06.59+0800 [App/0]      ERR TypeError: Cannot read property 'rows' of undefined
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at Object.exports.handle (/home/vcap/app/node_modules/nano/node_modules/errs/lib/errs.js:206:5)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at Request.emit (events.js:172:7)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at Request.<anonymous> (/home/vcap/app/node_modules/nano/node_modules/request/request.js:1142:14)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at emitOne (events.js:82:20)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at Request.emit (events.js:169:7)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/nano/node_modules/request/request.js:1096:12)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at endReadableNT (_stream_readable.js:921:12)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at nextTickCallbackWith2Args (node.js:442:9)
2016-08-14T22:57:06.59+0800 [App/0]      ERR     at process._tickCallback (node.js:356:17)

**Comment by jeffffrey** [comment]
commit 6e674b3a2b5990a629f647edbf4dd9b72f7adb42 fixed this issue.
